### ISSUE TITLE
Files are not getting watched or generated

### ISSUE THREAD

**Issue by nofxx** [guard/guard-coffeescript#18]
No files are getting watched or generated.

guard-coffeescript (2.0.1)

```
guard 'coffeescript', :input => 'app/js', :output => 'www/js'
guard 'haml', :input => 'app/html', :output => 'www'
guard 'sass', :input => 'app/css', :output => 'www/css'
```

Included other guards in the example because they are working perfectly.
Quadruple-checked my directory tree, it's all good. 
(also have rake working nice for the same task)

Guard run all:

```
04:47:50 - INFO - Run all
04:47:50 - INFO - Compile
04:47:50 - INFO - 04:47:50 AM Successfully generated 

04:47:50 - INFO - Successfully compiled haml to html!
> [#EB3785E208D4] # app/html/foo.haml -> www/foo.html

04:47:50 - INFO - Sass [0.00s] foo.sass -> foo.css
```

But again, nothing generated.

**Comment by e2** [comment]
guard-coffeescript 2.0.0 no longer adds the watching automatically, see:
https://github.com/guard/guard-coffeescript/releases/tag/v2.0.0

To debug cases like this, see: https://github.com/guard/guard/wiki/Understanding-Guard#debugging-complex-rules

The code you need is probably:
```ruby
input_dir = 'app/js'

coffeescript_options = {
  input: input_dir,
  output: 'www/js',
  patterns: [%r{^#{input_dir}/(.+\.(?:coffee|coffee\.md|litcoffee))$}]
}

guard 'coffeescript', coffeescript_options do
  coffeescript_options[:patterns].each { |pattern| watch(pattern) }
end

guard :haml, :input => 'app/html', :output => 'www' do
  watch(/^.+(\.html\.haml)$/)
end

guard 'sass', :input => 'sass', :output => 'css'
```

(NOTE: guard-sass works because it's still using the not-yet-deprecated Guard API)

**Comment by nofxx** [comment]
Thank you @e2 , working as a charm.

**Comment by e2** [comment]
Glad to help!
